version: '2'
services:
  dynamodb:
    container_name: dynamodb
    image: 'amazon/dynamodb-local:latest'
    entrypoint: java
    command: '-jar DynamoDBLocal.jar -sharedDb'
    restart: always
    volumes:
      - ${PWD}/data:/data
    ports:
      - '8080:8000'
      